// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::sql_types::{Float8, Array, Int4};
use chrono::{NaiveDateTime, NaiveDate};


#[derive(Queryable, Debug)]
pub struct Attende {
    pub id: i32,
    pub email: String,
    pub idevent: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Endl {
    pub id: i32,
    pub datetime: NaiveDateTime,
    pub timezone: String,
    pub idevent: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Event {
    pub id: i32,
    pub summary: String,
    pub location: String,
    pub description: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Override {
    pub id: i32,
    pub method: String,
    pub minutes: i32,
    pub idreminders: Option<i32>,
    pub idevent: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Recurrence {
    pub id: i32,
    pub rrule: String,
    pub idevent: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Reminder {
    pub id: i32,
    pub usedefault: bool,
    pub idevent: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Start {
    pub id: i32,
    pub datetime: NaiveDateTime,
    pub timezone: String,
    pub idevent: Option<i32>,
}

